### ISSUE TITLE
Call to a member function showForm() on null

### ISSUE THREAD

**Issue by janstieler** [youngcut/kirby-form-blocks#19]
Hi,
I'm not sure if I'm doing something wrong but I get the error `Call to a member function showForm() on null`.
I'm output the blocks not in a special way so I have no idea whats wrong.

Cheers

**Comment by youngcut** [comment]
Hm. curious. 🤔
Can you tell me you PHP and Kirby-Version and the way you implement the plugin.

**Comment by janstieler** [comment]
Hi,
PHP 7.4.29 and Kirby 3.6.6.
I use it inside a Layout. Here a Part of my blueprint:
```
title: Default
# preset: page
pages: false

tabs:
  content:
    label: Content
    icon: text
    columns:
      left:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              layout:
                type: layout
                layouts:
                  - "1/1"
                  - "1/2, 1/2"
                  - "1/3, 1/3, 1/3"
                  - "1/4, 1/4, 1/4, 1/4"
                fieldsets:
                  - heading
                  - markdown
                  - image
                  - link-button
                  - maps
                  - form
                  - line
                  - grid
                settings:
                  fields:
                    class:
                      type: text
                      width: 1/2
                    id:
                      type: text
                      width: 1/2
                    textstyleuc:
                      label: Text in Großbuchstaben
                      type: toggle
…
```
